name: bloc_example
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # state
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # create model automation
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  # store
  shared_preferences: ^2.0.15
  # network
  dio: ^4.0.6
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
flutter:
  uses-material-design: true
